In [1]:
import numpy as np
import matplotlib.pyplot as plt

data_file = np.loadtxt("data_file.txt", delimiter = ",")

time = data_file[:,0]

In [2]:
time[0:5]

array([1.39848889e+09, 1.39848889e+09, 1.39848889e+09, 1.39848890e+09,
       1.39848890e+09])

In [3]:
time = time - time[0]
time[0:5]

array([0.        , 0.99900007, 2.98600006, 5.85600019, 6.85500002])

In [4]:
data_file[0]

array([1.39848889e+09, 4.06821114e+02, 4.14730400e+02, 3.73126443e+02,
       3.75749231e+02,            nan,            nan,            nan,
                  nan])

In [6]:
sensors = data_file[:, 1:5]